# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text=b'What is included in this tem, e.g. cheese, brown bread, etc', max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=250)),
                ('time_to_deliver', models.DateTimeField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2016, 12, 25, 20, 51, 53, 302221, tzinfo=utc))])),
                ('time_delivered', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'N', b'New'), (b'P', b'Processing'), (b'O', b'On the way'), (b'D', b'Delivered')], default=b'N', max_length=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='burger_api.MenuItem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='burger_api.Order')),
            ],
        ),
    ]
