# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_api', '0002_auto_20161225_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_to_deliver',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
